-- WHY this migration is hand-written, not generated by `prisma migrate dev`:
-- Prisma's schema.prisma DSL has no concept of a PostgreSQL EXCLUDE
-- constraint - it only understands @unique, @@unique, and @@index. This
-- constraint is the ENTIRE mechanism that guarantees no double-booking
-- (spec section 3.3, the hard requirement of this whole POC), so it has to
-- be added by hand. Prisma still tracks that this migration ran (recorded
-- in the _prisma_migrations table, applied via `prisma migrate deploy`
-- exactly like any generated migration) - it just doesn't "understand"
-- the constraint's meaning, only Postgres needs to.
--
-- WHY an EXCLUDE constraint, and not the other two reasonable approaches:
--
--   vs. SERIALIZABLE transaction + retry-on-conflict:
--     A serializable transaction only detects the conflict at COMMIT time,
--     via a serialization failure the application then has to catch and
--     retry. That pushes real complexity (retry loops, backoff, deciding
--     how many times to retry) into application code to reimplement
--     something Postgres already does natively and more cheaply at the
--     constraint level.
--
--   vs. row locking (SELECT ... FOR UPDATE on the room, before inserting):
--     This only protects concurrent writers that go through the SAME code
--     path and remember to take the lock first. Any future code path - a
--     script, an admin tool, a bug, a second service - that inserts into
--     "bookings" without taking that lock silently reintroduces
--     double-booking. It is only as safe as every caller's discipline.
--
--   An EXCLUDE constraint is enforced by the TABLE itself, unconditionally,
--   for every writer, forever - impossible to bypass by accident, and it
--   raises one single, well-known Postgres error code (23P01,
--   exclusion_violation) that the app catches in exactly one place
--   (src/middleware/errorHandler.ts) and translates to a clean 409
--   BOOKING_CONFLICT response.

-- btree_gist supplies the "=" operator class for TEXT columns (our room_id
-- is a UUID stored as text) so it can be combined with a range type's "&&"
-- (overlap) operator inside a single GiST exclusion constraint. Without
-- this extension, a GiST index only knows how to exclude on the range
-- column by itself - it has no way to also require "AND it's the SAME
-- room_id" in the same constraint.
CREATE EXTENSION IF NOT EXISTS btree_gist;

-- The guarantee itself:
--   room_id WITH =                              -> only compare bookings for the SAME room
--   tstzrange(start_time, end_time, '[)') WITH &&  -> ...whose time ranges overlap
--
-- '[)' bound = inclusive start, exclusive end. A booking ending at 11:00
-- and one starting at 11:00 do NOT overlap under this bound - this matches
-- how the availability-search query (rooms.service.ts) computes overlap
-- too, so both the DB-enforced guarantee and the read-side search agree on
-- exactly what "conflicting" means.
--
-- WHERE (status = 'CONFIRMED') makes this a PARTIAL exclusion constraint:
-- a CANCELLED booking is invisible to it. This is what makes cancelling a
-- booking immediately free its slot for someone else (spec section 3.4) -
-- without this WHERE clause, a soft-cancelled row would block its room+time
-- forever, since the constraint would still see it as an active occupant.
-- NOTE on 42P17 ("functions in index expression must be marked IMMUTABLE"):
-- the real cause here is that "start_time"/"end_time" are actually
-- `timestamp` (no time zone) columns - not `timestamptz` as this comment
-- originally assumed. Calling tstzrange() (or any wrapper function typed
-- to take timestamptz) on them forces an IMPLICIT timestamp->timestamptz
-- cast on each argument first, and *that* cast is STABLE (it depends on
-- the session's timezone setting), which poisons the expression before
-- the range constructor even runs - no amount of declaring a wrapper
-- function IMMUTABLE fixes it, since the non-immutable part happens before
-- the wrapper is called.
--
-- The fix is to use `tsrange` (a plain timestamp range, matching the
-- actual column type) instead of `tstzrange` - no timezone-dependent cast
-- is involved at all, so the expression is genuinely immutable.
ALTER TABLE "bookings"
  ADD CONSTRAINT bookings_no_overlap
  EXCLUDE USING gist (
    room_id WITH =,
    tsrange("start_time", "end_time", '[)') WITH &&
  )
  WHERE (status = 'CONFIRMED');
