-- WHY this migration is hand-written, not generated by `prisma migrate dev`:
-- Prisma's schema.prisma DSL only understands B-tree @@index. The name/
-- location search added to GET /rooms and GET /rooms/search uses
-- case-insensitive substring matching (ILIKE '%term%'), which a B-tree
-- index cannot accelerate at all - a B-tree can only serve a PREFIX match
-- ("starts with"), not "contains anywhere in the string". Without a
-- trigram index, ILIKE '%term%' on rooms(name) forces a full sequential
-- scan on every search, which is exactly the "load everything, filter
-- afterward" cost the spec explicitly forbids for room search - the query
-- itself was already a real WHERE clause, but an unindexed one still pays
-- that cost under the hood.
--
-- pg_trgm decomposes each string into overlapping 3-character sequences
-- ("trigrams") and a GIN index over those trigrams lets Postgres find rows
-- containing a given substring anywhere in the column, not just as a
-- prefix - exactly what ILIKE '%term%' needs.
CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE INDEX rooms_name_trgm_idx ON "rooms" USING gin ("name" gin_trgm_ops);
CREATE INDEX rooms_location_trgm_idx ON "rooms" USING gin ("location" gin_trgm_ops);
